version: 2
updates:
- package-ecosystem: nuget
  directories:
      - /NekoPlayer.App
      - /NekoPlayer.Desktop
      - /NekoPlayer.Desktop.Windows
  schedule:
      interval: daily
  commit-message:
      prefix: deps
  labels:
      - dependencies
  open-pull-requests-limit: 5
