<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Project">
    <TargetFramework>net8.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <OutputType>WinExe</OutputType>
    <AssemblyName>NekoPlayer</AssemblyName>
    <ApplicationIcon>nekoplayer_app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.0.0</Version>
    <FileVersion>0.0.0</FileVersion>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Velopack" Version="1.2.0" />
  </ItemGroup>
  <ItemGroup Label="Project References">
    <ProjectReference Include="..\NekoPlayer.App\NekoPlayer.App.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appIcon.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="bassloud.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\bin\win-x64\ffmpeg.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\linux-x64\libavcodec.so.62">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\linux-x64\libavformat.so.62">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\linux-x64\libavutil.so.60">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\linux-x64\libswscale.so.9">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\windows-x64-fix\avcodec-62.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\windows-x64-fix\avdevice-62.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\windows-x64-fix\avfilter-11.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\windows-x64-fix\avformat-62.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\windows-x64-fix\avutil-60.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\windows-x64-fix\swresample-6.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="FFmpeg\windows-x64-fix\swscale-9.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="libbassloud.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="nekoplayer_app.bmp">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="nekoplayer_app.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\linux-x64\native\libbassloud.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="runtimes\win-x64\native\bassloud.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="yt-dlp.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="yt-dlp_linux">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" />
  </ItemGroup>
</Project>
